### ISSUE TITLE
Přidání zobrazení otáček rotoru

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/flight_review#1]
Ke grafům by bylo potřeba přidat záznam otáček rotoru.  Nejvhodnější by zřejmě bylo tuto datovou řadu doplnit do grafu Airspeed.

**Comment by slimonslimon** [comment]
zatím jsem to tam umístil jako extra graf.

**Comment by slimonslimon** [comment]
pořadí grafů lze ve zdrojáku zpřeházet

**Comment by slimonslimon** [comment]
Tohle bude potřeba upravit pro nová měření s oto/min

**Comment by kaklik** [comment]
Všiml jsem si, že jeden z posledních logů obsahuje divnost: 

![image](https://user-images.githubusercontent.com/1194177/49591142-eabff400-f96d-11e8-9093-10bf2827e077.png)

Fyzikálně, ale není možné, aby se otáčky rotoru změnily takto rychle. Proto zřejmě musí jít o nějakou chybu měření. Buď elektrickou, mechanickou, nebo softwarovou.

Záznam je z logu 25-11-2018 14:58

**Comment by kaklik** [comment]
Zatím vyřešeno.
