### ISSUE TITLE
Přidání náhledu na stránku s přehledem logů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/flight_review#2]
Stránka s přehledem logů https://logs.px4.io/browse
neobsahuje dost údajů k tomu, aby mezi logy bylo možné něco nalézt. 
Zejména by pomohl náhled trasy v mapce.

**Comment by slimonslimon** [comment]
náhled trasy na mapě, to je mi přijde trochu dost nereálné, ale možná se pletu...

(a nejezdí se zatím pořád stejná trasa?)

**Comment by kaklik** [comment]
Úplně stejná trasa se nejezdí. Obyvkle tam jsou vidět různé variace, kterými se jednotlivé pokusy liší. 
Ten náhled je super, :) Kdyby jsi to ještě trochu zoptimalizoval, aby ten náhled lépe využíval plochu, kterou má k dispozici, tak by myslím stálo za to z toho udělat pull-request do mainstreamu. Myslím že by to využili i další. :)

**Comment by roman-dvorak** [comment]
Bylo by také fajn, aby se náhled při najetí myší trošku zvětšil. Myslím, že by se pro to mohlo použít pouze CSS3

Toto přidat k CSS třídě obrázku
```
transition: all 0.5s ease-in-out;
```
A při akci `hover`:
```
transform: scale(7);
```
![snimek obrazovky porizeny 2018-12-02 21-09-50](https://user-images.githubusercontent.com/5196729/49344437-6d4b6980-f677-11e8-9728-ef3ce2ae5a9c.png)


A velmi se ten seznam zpřehlednil :)

**Comment by slimonslimon** [comment]
to mne napadlo, ale nejdřív jsem chtěl vědět, zda je to zhruba to co jste chtěli. Tak jsem nevěděl jak to udělat :-D

**Comment by slimonslimon** [comment]
Jo k tomu pull requestu -> nevím zda se jim bude líbit postup, který jsem zvolil -> ten náhled se vygeneruje při prvním zobrazení grafů a pak se tahá jako obrázek uložený na disku. Například jsem vůbec neztrácel čas tím abych koukal jak mají řešené promazávání starých logů a podobně...

**Comment by kaklik** [comment]
@slimonslimon Myslím, že by se mohlo vyplatit do toho pull-requestu investovat ještě trochu času, aby ho přijali.   Ušetří to čas spojený s tím, až budeme potřebovat nějaké jejich nové úpravy zamegrovat do našeho momentálně běžícího kódu, který pak už bude starý.

**Comment by slimonslimon** [comment]
Toto považuji momentálně za vyřešené - na pull request si udělám extra issue vygenerování nových náhledů s menším bílím místem spustím večer.
