### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by slimonslimon** [ThunderFly-aerospace/flight_review#3]
byl by asi dobré umístit tento upravený nástroj na nějaký server.

**Comment by slimonslimon** [comment]
Momentálně jsme to vyřešil spuštěním na serveru: http://vz.fjfi.cvut.cz:8080/

**Comment by kaklik** [comment]
Na tom co jsem navrhoval bude aktualizované ubuntu.  Až to proběhne, tak dám vědět.

**Comment by slimonslimon** [comment]
pokud tam bude nějaké 16.04 a budou tam nainstalovány následující balíky (možná jsou jejich jména malinko jiná):
python3
python3-pip
libfftw-dev
sqlite3
a bude moci prostýý uživatel (aka slimonslimon) použít pip tak to nebude problém.

**Comment by kaklik** [comment]
server pro logy byl zřízen.
