### ISSUE TITLE
Řazení tabulky s logy

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/flight_review#4]
Teď když je v databázi nahráno více logů, tak jsem si všiml, že se neřadí podle času logu ale podle "upload date". 
Což je pro naše potřeby myslím úplně k ničemu. 

@roman-dvorak  Nemáš na intranetu vyzkoušené nějaké řešení pro řazení tabulek?  Třeba nějakými klikacími šipkami u jména sloupce, nebo tak něco. 

Taky mě i dost štve, že při otevírání logu nelze kliknout prostě na řádek, ale musí se najet myší až na ten jedinný klikací odkaz v sloupci "upload date".

**Comment by roman-dvorak** [comment]
Tam používám JS knihovnu 'Tabulator'.

Mělo by stačit na současnou tabulku jen spustit jednu fuknci knihovny a to by mělo šipky pro řazení přidat. 
V intranetu to nepoužívám tlakhle ale rovnou pomocí této knihovny asynchroně vytvářím tabulku z JSON dat. Což je tady asi zbytečné. Pro účely intranetu jsem musel upravit některé funkce pro vykreslování jednotlivých buněk. Ale to by v tomto případu nemuselo být potřeba.

Předpokládám, že úprava, aby byl klikací celý řádek je jen úprava nějaké šablony.

**Comment by kaklik** [comment]
Tabulku s logy je zřejmě nutné řadit přes všechny logy. Což znamená řadit podle informací, které se z logu načtou a uloží do databáze.  
Pravděpodobně by mělo jít o tyto údaje, podle kterých má smysl logy řadit: 

- Čas počátku logu (Logging Start)
- Logging Duration

Potom také parametry u kterých si nejsem jistý, jestli je log obsahu je, nebo je potřeba výpočet.
- Dropouts
- Max Altitude Difference
- Pak by se hodil parametr, který popisuje celkovou spotřebovanou energii. V logu je to v grafu Power, jako veličina "discharged amount", obávam se ale, že pro získání této hodnoty bude potřeba nějaký významější výpočet.

**Comment by slimonslimon** [comment]
Základní řazení je implemntováno,  čas začátku a doba letu je také přidána 
-> nakonec to tak razantní zásah do architektury nebyl
-> není problém tam asi přidat další sloupečky,když budeme vědět jak je z logu spočítat.

**Comment by kaklik** [comment]
Ok, myslím, že je to vyřešené.

**Comment by slimonslimon** [comment]
Ještě komentář - hodnoty těch nových sloupečků se musí přidat do databáze, aby se pdle nich dalo řadit
