### ISSUE TITLE
Zobrazení letových režimů

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/flight_review#5]
Z nějakého důvodu nevidím v seznamu nic ve sloupci  "flight modes".

Pro porovnání 

![image](https://user-images.githubusercontent.com/1194177/49370269-fdc78f80-f6f3-11e8-8a7b-93edc7cff9a8.png)

A náš upravený seznam: 

![image](https://user-images.githubusercontent.com/1194177/49370307-12a42300-f6f4-11e8-9006-b0face3c67ee.png)

**Comment by slimonslimon** [comment]
Aha, tak jsem to přeci jen rozbil...

**Comment by slimonslimon** [comment]
Fixnuto - sice nevím vůbec co to dělá a jak, ale náhodným programováním jsme to opravil:
https://github.com/ThunderFly-aerospace/flight_review/commit/6654c9ebd7aa3715e3fb394e625ecef582cebe5a#diff-5d2e4746c1947fcad7e1111dc55a78ea
